### ISSUE TITLE
Allow replacing (or translating) the "Today" button text

### ISSUE THREAD

**Issue by rogerclotet** [jovanjenjic/react-lightweight-calendar#34]
Setting the `locale` prop to another language works for most of the text of the calendar, but the "Today" button is very noticeable and its `label` is hardcoded [here](https://github.com/jovanjenjic/react-lightweight-calendar/blob/6b6c4e12a24606b9d57ec0a20777f6db4fdfe640/src/components/Calendar/CalendarNavigation.tsx#L46).

To follow the design of the library API, I propose adding a new prop `todayLabel` that can customize this, with "Today" as its default value. I think this is the more practical way to allow customizing it, and it's a fairly easy and non-breaking change.

If you're okay with it, I can open a PR with this change.

**Comment by jovanjenjic** [comment]
It's ok for me. Feel free to open pull request
